name: Build

on:
  push:
    branches: [ trunk ]
  schedule:
    - cron: '15 0 * * *'

jobs:
  update_codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -O /tmp/ucm-linux.tar.gz https://github.com/unisonweb/unison/releases/download/release%2FM3/ucm-linux.tar.gz
          tar -x -z -f /tmp/ucm-linux.tar.gz -C /usr/local/bin ./ucm
          git config user.name github-actions
          git config user.email github-actions@github.com
          PATH="${PATH}:/usr/local/bin" ./build.sh
          git add .unison && git commit -m "Update share codebase [skip actions]" && git push || echo "no changes to push"
